name: Run e2e Tests

on: [pull_request]

jobs:
    run-e2e-tests:
        name: Run e2e Tests
        runs-on: ubuntu-latest

        services:
            postgres:
                image: bitnami/postgresql
                ports: 
                    - 5432:5432
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_DB: check-gym
                options: >-
                    --health-cmd pg_isready
                    --health-interval 5s
                    --health-timeout 5s
                    --health-retries 10

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - uses: pnpm/action-setup@v4
              name: Install pnpm

            - name: Install node.js
              uses: actions/setup-node@v4
              with:
                node-version: 24
                cache: "pnpm"

            - run: pnpm install --frozen-lockfile
            - run: pnpm run test:e2e
              env:
                JWT_SECRET: testing
                DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/check-gym"